### ISSUE TITLE
Error :/

### ISSUE THREAD

**Issue by JohnNielse** [kanadeko/Kuro#21]
getting error when doing the `npm install` command.

Log file attached.

[npm-debug.txt](https://github.com/kanadeko/Kuro/files/818579/npm-debug.txt)

**Comment by giantcow** [comment]
`npm install npm -g`

And update node using [n](https://github.com/tj/n)

EDIT: nvm n doesn't support Windows yet. https://nodejs.org/en/

**Comment by JohnNielse** [comment]
Still getting the same Error. Node updated to latest version too

**Comment by MAPReiff** [comment]
I'm haveing the exact same issue.

**Comment by giantcow** [comment]
1) Uninstall C++ 2010 x64 and x86 versions
2) Make sure you have Python 2 (or 3) installed
3) Install the [Windows C++ Build Tools 2015](http://landinghub.visualstudio.com/visual-cpp-build-tools). If you're running Windows 7 you need to install [.NET 4.5.1](http://www.microsoft.com/en-us/download/details.aspx?id=40773)
4) Run this in CMD `npm config set msvs_version 2015 --global`

**Comment by JohnNielse** [comment]
Nothing Changed :/ 

Still getting the same error.

Tried doing it on a fresh VM. Same problem there

**Comment by Pitu** [comment]
Are you trying to make it work on Windows or Linux?
And what version of npm and node are you running?

**Comment by MAPReiff** [comment]
Like @Sonanio said, still happening. Windows 10 Pro, NPM version 4.1.2, Node version 7.5.0

**Comment by Pitu** [comment]
@MAPReiff @Sonanio I haven't forgotten about you people. Could you please try the following:

1. Ensure you have Python installed and it's in your path
2. Run `npm install --global --production windows-build-tools`
3. Try to run the bot again.

**EDIT**: Forget about this. Just found the culprit on one of the modules and removed it. Please clone again in an empty folder and install as readme suggests.
