### ISSUE TITLE
Consider replacing kitsu.js with kitsu

### ISSUE THREAD

**Issue by wopian** [kanadeko/Kuro#30]
[kitsu.js](https://yarnpkg.com/en/package/kitsu.js) is deprecated in favour of the more feature complete [kitsu](https://yarnpkg.com/en/package/kitsu) package that is fully JSON-API compliant.

Based on [your current usage], search implementation would be something like:

```js
const Kitsu = require('kitsu')
const kitsu = new Kitsu()

kitsu.fetch('anime', {
  filter: {
    text: search
  }
}).then({ data } => {
  if (data.length === 0) {
    return msg.edit(`No results found for: **${search}**`)
  }
  return prepareEmbed(msg, data[0])
})
```

[your current usage]:https://github.com/Pitu/Kuro/blob/74a96c1b360f223a8f1883282c9a7e8842e34da5/commands/anime.js

**Comment by Pitu** [comment]
Thanks for the suggestion! 

Given the new pro-active stance of Discord against disallowing the usage of self-bots, I'm unsure if it's worth supporting this project any longer. I'll dig around the relevant Discord servers to see if this is still going and decide based on that if switching libraries is worth it or not.
